/*
 * This project was created by Donovan Adrian and any
 * edits or changes must be confirmed as valid by Donovan
 * with written consent under any circumstance.
 */

//COMMON PAGE VARS
var offlineModal;
var offlineModalSpan;
var printModal;
var printTitle;
var printFilament;
var printTime;
var printSize;
var printInfill;
var printPrice;
var printStatus;
var printUpdateBtn;

//LOGIN VARS
var userNameInput;
var pinInput;
var loginBtn;
var loginGuestBtn;
var loginInfoFail;
var loginInfoSuccess;
var signUpFld;

//HOME VARS
var printListContainer;
var printPlaceholder;
var upgradeUserBtn;
var addPrintBtn;
var printDeleteBtn;
var editPrintModal;
var editPrintTitle;
var editPrintFilament;
var editPrintFilamentContent;
var editPrintFilamentPlaceholder;
var editPrintSize;
var editPrintSizeS;
var editPrintSizeM;
var editPrintSizeL;
var editPrintInfill;
var editPrintInfillNormal;
var editPrintInfillL;
var editPrintInfillXL;
var editPrintInfillXXL;
var editPrintInfillXXXL;
var editPrintTime;
var editPrintPrice;
var editPrintInfo;
var editPrintUpdateBtn;
var editPrintCancelBtn;

//SETTINGS VARS
var editNameInput;
var editUserNameInput;
var editPinInput;
var editConfirmPinInput;
var editUpdateUserBtn;

//ADMIN VARS
var userListContainer;
var userListPlaceholder;
var userModal;
var userTitle;
var userUID;
var userName;
var userUserName;
var userPassword;
var userPrints;
var userBill;
var userFilament;
var userAdminStatus;
var userShowPrintsBtn;
var userDeleteBtn;
var guestModal;
var guestTitle;
var guestUID;
var guestName;
var guestPin;
var guestPrints;
var guestBill;
var guestFilament;
var guestShowPrintsBtn;
var guestDeleteBtn;
var printListModal;
var printListModalTitle;
var printListModalContainer;
var printListModalPlaceholder;
var printStatusOrdered;
var printStatusPrinting;
var printStatusComplete;
var printStatusOther;
var printStatusNew;
var printCancelBtn;

//FILAMENT VARS
var filamentListContainer;
var filamentPlaceholder;
var addFilamentBtn;
var filamentModal;
var filamentTitle;
var filamentType;
var filamentWeight;
var filamentThickness;
var filamentCostPerRoll;
var filamentCostPerGram;
var filamentUserCount;
var filamentUpdateBtn;
var filamentDeleteBtn;
var editFilamentModal;
var editFilamentTitle;
var filamentEditTitle;
var filamentEditFilament;
var filamentEditFilamentContent;
var filamentTypePlaceholder;
var filamentEditFilamentNew;
var filamentEditWeight;
var filamentWeightXS;
var filamentWeightS;
var filamentWeightM;
var filamentWeightL;
var filamentWeightXL;
var filamentWeightOther;
var filamentEditWeightNew;
var filamentEditThickness;
var filamentThicknessS;
var filamentThicknessM;
var filamentThicknessL;
var filamentThicknessOther;
var filamentEditThicknessNew;
var filamentEditCostPerRoll;
var filamentEditCostPerGram;
var filamentEditUserCount;
var filamentEditInfo;
var filamentEditUpdate;
var filamentEditCancel;